[firebase]
type = "service_account"
project_id = "quiz-runner-2e48a"
private_key_id = "b0e3f813f8384c177e4af0bfe9d6386fe2bc7545"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDI76cyvnjyfvcs
IQ72H+YckHEwZWx5Q9zBela4gHgiKatNL+hkTXJlrnHqyJypGosZzvZUdNBw4qnT
+HUIu+MdOVoLlYDmWKoEkRFnK2efDgJ1ItlNIYkfMDKf2CqMkFyEm/9O2cP33Qnn
iAsBsq/0WFXHTKOQolfyqRd1PpgXTsgJAXNuQD3d6z3AmnctmnFegE/rkkt/bVoU
40bvtzD80RccDp+kKX6c1I3c5272K5eutylW2s1nei1e//DMvZQYnLKN+bq0229F
QBPWBESlrDeCS6xmSS8VX9KIEt8b/vxtnQiVK6F4fT02xnd38rJpa/p7dGxJK9n/
ndsZ1M33AgMBAAECggEAFr9lfaMpQhq0P3SxTZUoPIzwTiWioB/Z+rVaN/ejTLV2
79K/9mBQ1nNnRh3Wo8ueJRp/Bz9U5v1iHd3U3LDt8ehaP1F6OZmetcxOh2WB4knN
vBZpOggqjoiq/S7rB5AYST2igPoPlhyZ+xzgUh2Ojz+o26/bceD5ypObVOn0gel1
Q6hiIbvX0TosuUpzTjrlrVeZ+PO2CgBF3oCHkg99roSbNmapFOGhBLD4pY2VGvm5
qtVxRUsEQWNypkfIaVHtKKIADgLrIjhYowHlCjrFA3nH5qRINxopVw1cdgYP/XZ7
A+JRmz3ov+H3sDEkTx0tV4sss+rRs1vPBcF+vYxXYQKBgQDqejROAc5OZ4eg6cC/
5JHwfL5m0KenEa2rYUzAeG2ayCjun7rIiD6kFxqXGHieSnY0JQFP9wjLRM3CulgT
pZ0YWjdk9ANxV0W9ghbNr6YFGZvnMOzxWfZria33uSgKT7PVkyys0cAntfykbSKZ
H2WEebNfJ9szaGwE8BgV8tXF7wKBgQDbYUpnk3th0bvyG1ARkkpo/xxzbQZrLyuA
djmuyvVnn9c7RG9HFI4QJ3vPTJRbMsa7338Bpm32BZulZvJkgp77sJ96Frg1RIeK
ft6+Ju1CwlLEj2z8ZdZ8kAqGYrdfhbRIJiRCXDjkdGfQfs5KrljmpfqSHFbBvUuz
PQEp9hnAeQKBgQCId61/hT+MlGb0uXeMd7yUqhWrA1/ANeLNLykbkDvCbSKdl2t/
kQRcPnIkZIK3JgFb4fm8j7uXiqjy37+pV6dx5/f7kqV6Tt/xJwicl9FZgIkjam9N
HR31gsE0v5fVQIQbFrhWsRFUS3AKRtZvJj3Qd4B1Ll4+slTEHvT1uUrAEwKBgQDY
TOfYkdBgFTPzNTzP5mZZedcqc3+VpM+GfIrJLbGi9zV2aTYyZjDf+p4XOVE5Tiom
SOlnzhmzLbpV7dfmg+ePD4leDhKX6radNhQWdjkOzpxe029IuHwvGrJV5/UXSLQF
Qx4TE+zAS4mkR7LMbXSYDWSuNSTRJvwBgI+qOM0ROQKBgE3ZZEwlE6ezgmVETfFi
WLZ+tLOwpaeaNNSI5ILrlgLxpfQp7tTs0uMZWOEmz64oujTafCPxxTRwQTct5qFC
KiMdNOr85tyHTdbJYqLzwItmOy2qeCPEXQaC+JVwylpyD60ayVfBckT+D2BK8b2F
jbm4nUhEEH5NO2/y66aGC1zg
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@quiz-runner-2e48a.iam.gserviceaccount.com"
client_id = "109042114139250092562"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40quiz-runner-2e48a.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
